dist: xenial
sudo: required
language: python
python:
  - 3.6
addons:
  chrome: stable
  firefox: latest
before_install:
  - wget -N http://chromedriver.storage.googleapis.com/81.0.4044.138/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo cp -f ~/chromedriver /usr/local/bin
  - sudo chmod +x /usr/local/bin/chromedriver
services:
  - xvfb
install:
  - python --version
  - pip install -r requirements.txt
env:
  - BROWSER=firefox HEADLESS=1
script:
  - set -e
  - whereis google-chrome-stable
  - google-chrome-stable --version
  - whereis chromedriver
  - python -m unittest -v test.test_kiwisaver.KiwiSaverCalculator
