dist: xenial
language: python
python:
  - 3.8
addons:
  chrome: stable
before_install:
  - wget -N http://chromedriver.storage.googleapis.com/81.0.4044.138/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
install:
  - python --version
  - pip install -r requirements.txt
services:
  - xvfb
script:
  - set -e
  - whereis google-chrome-stable
  - google-chrome-stable --version
  - whereis chromedriver
  - python -m unittest discover
