dist: xenial
sudo: required
language: python
python:
  - 3.8
addons:
  chrome: stable
services:
  - xvfb
install:
  - python --version
  - pip install -r requirements.txt
script:
  - set -e
  - whereis google-chrome-stable
  - google-chrome-stable --version
  - whereis chromedriver
  - python -m unittest -v test.test_kiwisaver.KiwiSaverCalculator
